### ISSUE TITLE
Published npm package is missing precompiled JavaScript

### ISSUE THREAD

**Issue by myabc** [efacilitation/gulp-livingstyleguide#3]
Despite change in a3cc21e7, build artefacts (i.e. the compiled `index.js`) are missing from the npm-published package.

```javascript
// gulpfile.js
var livingstyleguide = require('gulp-livingstyleguide');
```

will result in 

```
Error: Cannot find module 'gulp-livingstyleguide'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/alexbcoles/git-repos/openproject/frontend/gulpfile.js:36:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by johannesbecker** [comment]
I guess this is related to https://github.com/npm/npm/issues/5082 - can't get it to work right now, but I'll keep trying.

**Comment by johannesbecker** [comment]
Well, actually there was a files array entry in the package.json which did not include index.js - d'oh. Fixed, should work as expected. Thanks for reporting.

**Comment by myabc** [comment]
@johannesbecker thanks!
