### ISSUE TITLE
Plugin broken in Windows because of semicolon delimiter

### ISSUE THREAD

**Issue by jviotti** [efacilitation/gulp-livingstyleguide#5]
I get the following errors on Windows 10 when passing a configuration file that lives in `styleguide/styleguide.html.lsg`:

```sh
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                  ^

Error: ENOENT: no such file or directory, open 'C:\Users\Juan Cruz Viotti\Projects\habitat\styleguide\styleguide.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at C:\Users\Juan Cruz Viotti\Projects\habitat\node_modules\gulp-livingstyleguide\index.js:57:31
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

By investigating the issue, I see that `styleguide\styleguide.html` is generated by `bundler exec livingstyleguide compile styleguide/styleguide.html.lsg`.

Running the command with the semicolon, as done here: https://github.com/efacilitation/gulp-livingstyleguide/blob/master/index.coffee#L29, reveals an issue that is being swallowed by not checking the `stderr` variable:

```sh
C:\Users\Juan Cruz Viotti\Projects\habitat>bundle exec livingstyleguide compile styleguide/styleguide.html.lsg;
C:/Ruby21/lib/ruby/gems/2.1.0/gems/livingstyleguide-1.2.2/lib/livingstyleguide/command_line_interface.rb:30:in `read': No such file or directory @ rb_sysopen - styleguide/styleguide.html.lsg; (Errno::ENOENT)
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/livingstyleguide-1.2.2/lib/livingstyleguide/command_line_interface.rb:30:in `input'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/livingstyleguide-1.2.2/lib/livingstyleguide/command_line_interface.rb:15:in `block in compile'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/tilt-2.0.1/lib/tilt/template.rb:77:in `call'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/tilt-2.0.1/lib/tilt/template.rb:77:in `initialize'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/livingstyleguide-1.2.2/lib/livingstyleguide/command_line_interface.rb:14:in `new'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/livingstyleguide-1.2.2/lib/livingstyleguide/command_line_interface.rb:14:in `compile'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/livingstyleguide-1.2.2/bin/livingstyleguide:6:in `<top (required)>'
        from C:/Ruby21/bin/livingstyleguide:23:in `load'
```

Removing the semicolon makes the plugin work on Windows again.

```sh
C:\Users\Juan Cruz Viotti\Projects\habitat>bundle exec livingstyleguide compile styleguide/styleguide.html.lsg
Successfully generated a living style guide at styleguide/styleguide.html.
```

Is there a reason we're still keeping the semicolon?

Happy to make a PR removing the semicolon and checking the value of `stderr`.

**Comment by mwager** [comment]
Ok, we are not using this on windows, but if you wanna make a PR we will probably merge it.
